comp3297proj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('trans19.urls')),
    path('admin/', admin.site.urls),
]

trans19/urls.py
from django.urls import path
from . import views

app_name = 'trans19'

urlpatterns = [
    path('', views.index, name='index'),
    path('locations/', views.locations, name='locations'),
    path('patients/', views.patients, name='patients'),
    path('patients/<int:patient_id>/', views.detail, name='detail'),
    path('patients/new/', views.PatientCreate.as_view(), name='patient_new'),
    path('patients/<int:pk>/edit', views.PatientUpdate.as_view(), name='patient_edit'),
    path('patients/<int:pk>/delete', views.PatientDelete.as_view(), name='patient_delete'),
    path('locations/new', views.location_new, name='location_new'),
    path('locations/<int:pk>/edit', views.location_edit, name='location_edit'),
    path('locations/<int:pk>/delete', views.LocationDelete.as_view(), name='location_delete'),
    path('connections/', views.connections, name='connections'),
]

trans19/models.py
from django.db import models


class Patient(models.Model):
    patient_name = models.CharField(max_length=200)
    patient_id = models.CharField(max_length=200)
    date_of_birth = models.DateField()
    date_case_confirmed = models.DateField()
    case_number = models.IntegerField(default=0, unique=True)

    def __str__(self):
        return self.patient_name


class Location(models.Model):
    location_name = models.CharField(max_length=200)
    DISTRICT_CHOICES = [
        ('Hong Kong Island', (
            ('Central and Western', 'Central and Western'),
            ('Eastern', 'Eastern'),
            ('Southern', 'Southern'),
            ('Wan Chai', 'Wan Chai'),
        )
         ),
        ('Kowloon', (
            ('Sham Shui Po', 'Sham Shui Po'),
            ('Kowloon City', 'Kowloon City'),
            ('Kwun Tong', 'Kwun Tong'),
            ('Wong Tai Sin', 'Wong Tai Sin'),
            ('Yau Tsim Mong', 'Yau Tsim Mong'),
        )
         ),
        ('New Teritories', (
            ('Islands', 'Islands'),
            ('Kwai Tsing', 'Kwai Tsing'),
            ('North', 'North'),
            ('Sai Kung', 'Sai Kung'),
            ('Sha Tin', 'Sha Tin'),
            ('Tai Po', 'Tai Po'),
            ('Tsuen Wan', 'Tsuen Wan'),
            ('Tuen Mun', 'Tuen Mun'),
            ('Yuen Long', 'Yuen Long'),
        )
         ),
    ]
    district = models.CharField(max_length=200, choices=DISTRICT_CHOICES)
    address = models.CharField(max_length=200)
    x_coord = models.IntegerField()
    y_coord = models.IntegerField()

    def __str__(self):
        return self.location_name


class Visit(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    date_from = models.DateField()
    date_to = models.DateField()
    detail = models.CharField(max_length=200)
    category = models.CharField(max_length=200)

    def __str__(self):
        return self.location.location_name

trans19/forms.py
from django import forms
from .models import Patient, Visit, Location
from django.forms import inlineformset_factory
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Fieldset, Div, HTML, ButtonHolder, Submit
from .custom_layout_object import *

import datetime


class LocationForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = '__all__'


class DateInput(forms.DateInput):
    input_type = 'date'


class VisitForm(forms.ModelForm):
    class Meta:
        model = Visit
        fields = '__all__'
        widgets = {
            'date_from': DateInput(),
            'date_to': DateInput(),
        }

    def clean(self):
        cleaned_data = super().clean()
        date_from = cleaned_data.get("date_from")
        date_to = cleaned_data.get("date_to")
        if date_from and date_to:
            if date_from > datetime.date.today():
                msg = "The date cannot be in the future!"
                self.add_error('date_from', msg)
            if date_to > datetime.date.today():
                msg = "The date cannot be in the future!"
                self.add_error('date_to', msg)
            if date_from > date_to:
                msg = "The date to cannot be earlier than the date from!"
                self.add_error('date_to', msg)


PatientFormSet = inlineformset_factory(
    Patient,
    Visit,
    form=VisitForm,
    extra=1,
    can_delete=True,
)


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        exclude = ()
        widgets = {
            'date_case_confirmed': DateInput(),
            'date_of_birth': DateInput(),
        }

    def clean(self):
        cleaned_data = super().clean()
        date_case = cleaned_data.get("date_case_confirmed")
        if date_case > datetime.date.today():
            msg = "The date cannot be in the future!"
            self.add_error('date_case_confirmed', msg)
        date_birth = cleaned_data.get("date_of_birth")
        if date_birth > datetime.date.today():
            msg = "The date cannot be in the future!"
            self.add_error('date_of_birth', msg)

    def __init__(self, *args, **kwargs):
        super(PatientForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3 create-label'
        self.helper.field_class = 'col-md-9'
        self.helper.layout = Layout(
            Div(
                Field('patient_name'),
                Field('patient_id'),
                Field('date_of_birth'),
                Field('date_case_confirmed'),
                Field('case_number'),
                Fieldset('Add Visits',
                    Formset('visits')),
                HTML("<br>"),
                ButtonHolder(Submit('submit', 'Save')),
                )
            )

trans19/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.db import transaction
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Patient, Location, Visit
from .forms import LocationForm, PatientForm, PatientFormSet

from datetime import timedelta


def index(request):
    num_cases = Patient.objects.all().count()
    context = {"num_cases": num_cases, "index": "active"}
    return render(request, 'trans19/index.html', context)


@login_required
def locations(request):
    latest_location_list = Location.objects.order_by('location_name')[:20]
    context = {'latest_location_list': latest_location_list, "location": "active"}
    return render(request, 'trans19/locations.html', context)


@login_required
def patients(request):
    latest_patient_list = Patient.objects.order_by('case_number')[:20]
    context = {'latest_patient_list': latest_patient_list, "patient": "active"}
    return render(request, 'trans19/patients.html', context)


@login_required
def detail(request, patient_id):
    patient = get_object_or_404(Patient, pk=patient_id)
    return render(request, 'trans19/detail.html', {'patient': patient})


@login_required
def location_new(request):
    if request.method == "POST":
        form = LocationForm(request.POST)
        if form.is_valid():
            location = form.save(commit=False)
            location.save()
            return redirect('trans19:locations')
    else:
        form = LocationForm()
    return render(request, 'trans19/addLocation.html', {'form': form})


@login_required
def location_edit(request, pk):
    location = get_object_or_404(Location, pk=pk)
    if request.method == "POST":
        form = LocationForm(request.POST, instance=location)
        if form.is_valid():
            location = form.save(commit=False)
            location.save()
            return redirect('trans19:locations')
    else:
        form = LocationForm(instance=location)
    return render(request, 'trans19/addLocation.html', {'form': form})


class LocationDelete(LoginRequiredMixin, DeleteView):
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'
    model = Location
    template_name = 'trans19/deleteLocation.html'
    success_url = reverse_lazy('trans19:locations')


class PatientCreate(LoginRequiredMixin, CreateView):
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'
    model = Patient
    template_name = 'trans19/addPatient.html'
    form_class = PatientForm
    success_url = None

    def get_context_data(self, **kwargs):
        data = super(PatientCreate, self).get_context_data(**kwargs)
        if self.request.POST:
            data['visits'] = PatientFormSet(self.request.POST)
        else:
            data['visits'] = PatientFormSet()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        visits = context['visits']
        with transaction.atomic():
            form.instance.created_by = self.request.user
            self.object = form.save()
            if visits.is_valid():
                visits.instance = self.object
                visits.save()
        return super(PatientCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('trans19:patients')


class PatientUpdate(LoginRequiredMixin, UpdateView):
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'
    model = Patient
    template_name = 'trans19/addPatient.html'
    form_class = PatientForm

    def get_context_data(self, **kwargs):
        data = super(PatientUpdate, self).get_context_data(**kwargs)
        if self.request.POST:
            data['visits'] = PatientFormSet(self.request.POST, instance=self.object)
        else:
            data['visits'] = PatientFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        visits = context['visits']
        with transaction.atomic():
            form.instance.created_by = self.request.user
            self.object = form.save()
            if visits.is_valid():
                visits.instance = self.object
                visits.save()
        return super(PatientUpdate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('trans19:patients')


class PatientDelete(LoginRequiredMixin, DeleteView):
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'
    model = Patient
    template_name = 'trans19/deletePatient.html'
    success_url = reverse_lazy('trans19:patients')


def is_epidemiologists(user):
    return user.groups.filter(name='Epidemiologists').exists()


@login_required
@user_passes_test(is_epidemiologists)
def connections(request):
    patient_case = request.GET.get('case_number')
    time_window = request.GET.get('time_window')
    if time_window:
        time_window = int(time_window)
    context = {"patient": patient_case, "connection": "active"}
    unfortunate_list = Visit.objects.none()
    visit_list = Visit.objects.filter(patient__case_number=patient_case).values(
        "location", "date_from", "date_to")
    for v in visit_list:
        unfortunate_list = unfortunate_list | Visit.objects.filter(
            location=v["location"]).filter(date_from__range=(
                v["date_from"] - timedelta(days=time_window),
                v["date_to"] + timedelta(days=time_window))) | Visit.objects.filter(
            location=v["location"]).filter(date_to__range=(
                v["date_from"] - timedelta(days=time_window),
                v["date_to"] + timedelta(days=time_window)))
    context['potential_patient_list'] = unfortunate_list.exclude(patient__case_number=patient_case)
    context['selected_patient'] = Patient.objects.filter(case_number=patient_case).values(
        "patient_name", "date_case_confirmed", "case_number")
    context['selected_patient_visit'] = Visit.objects.filter(patient__case_number=patient_case)

    return render(request, 'trans19/connections.html', context)

trans19/templates/trans19/addLocation.html
{% extends "trans19/layouts/base.html" %}

{% block content %}
    <div class="container-fluid my-5">
        <div class="card">
            <div class="card-header">
                Add Location
            </div>
            <div class="card-body">
               <form method="POST">{% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="save btn btn-primary">Save</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

trans19/templates/trans19/addPatient.html
{% extends "trans19/layouts/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="container-fluid my-5">
        <div class="card">
            <div class="card-header">
                Add Patient
            </div>
            <div class="card-body">
                {% crispy form %}
            </div>
        </div>
    </div>

{% endblock %}

trans19/templates/trans19/connections.html
{% extends "trans19/layouts/base.html" %}
{% block content %}
<div class="container my-5">
  <div class="card">
    <div class="card-header">
      Search Connections
    </div>
    <div class="card-body">
      <form method="GET">
        {% csrf_token %}
        <p>
          <label for="id_case_number">Case Number:</label>
          <input
            type="number"
            name="case_number"
            class="numberInput"
            required=""
            value="0"
            min="0"
            id="id_case_number"
          />
        </p>

        <p>
          <label for="id_time_window">Time Window:</label>
          <input
            type="number"
            name="time_window"
            class="numberInput"
            required=""
            value="0"
            min="0"
            id="id_time_window"
          />
        </p>

        <button type="submit" class="save btn btn-primary">Search</button>
      </form>
    </div>
  </div>
</div>
{% if selected_patient %}
    <div class="jumbotron">
        <h2 class="text-center">Search Results</h2>
    </div>
    <h3 class="text-center mt-5">Selected Patient</h3>
    <div class="table-responsive w-75 mx-auto mb-5">
        <table class="table table-bordered mt-3">
            <thead class="thead-light">
                <tr>
                    <th class="header">Case number</th>
                    <th class="header">Patient Name</th>
                    <th class="header">Date case confirmed</th>
              </tr>
            </thead>
            <tbody>
                <tr>
                    {% for patient in selected_patient %}
                    <td>{{ patient.case_number }}</td>
                    <td>{{ patient.patient_name }}</td>
                    <td>{{ patient.date_case_confirmed }}</td>
                    {% endfor %}
                </tr>
            </tbody>
        </table>
    </div>

<h3 class="text-center mt-5">Patient's Visits</h3>
    <div class="table-responsive w-75 mx-auto mb-5">
        <table class="table table-bordered mt-3">
            <thead class="thead-light">
                <tr>
                    <th class="header">Location Visited</th>
                    <th class="header">Date From</th>
                    <th class="header">Date To</th>
                    <th class="header">Detail</th>
                    <th class="header">Category</th>
              </tr>
            </thead>
            <tbody>
            {% for visit in selected_patient_visit %}
                <tr>
                    <td>{{ visit.location.location_name }}</td>
                    <td>{{ visit.date_from }}</td>
                    <td>{{ visit.date_to }}</td>
                    <td>{{ visit.detail }}</td>
                    <td>{{ visit.category }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>


<h3 class="text-center mt-5">Possible Connections</h3>
    <div class="table-responsive w-75 mx-auto mb-5">
        <table class="table table-bordered mt-3">
            <thead class="thead-light">
                <tr>
                    <th class="header">Case Number</th>
                    <th class="header">Patient Name</th>
                    <th class="header">Date case confirmed</th>
                    <th class="header">Location</th>
                    <th class="header">Date From</th>
                    <th class="header">Date To</th>
                    <th class="header">Detail</th>
                    <th class="header">Category</th>
              </tr>
            </thead>
            <tbody>
            {% for visit in potential_patient_list %}
                <tr>
                    <td>{{ visit.patient.case_number }}</td>
                    <td>{{ visit.patient.patient_name }}</td>
                    <td>{{ visit.patient.date_case_confirmed }}</td>
                    <td>{{ visit.location.location_name }}</td>
                    <td>{{ visit.date_from }}</td>
                    <td>{{ visit.date_to }}</td>
                    <td>{{ visit.detail }}</td>
                    <td>{{ visit.category }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% endif %}
{% endblock %}

trans19/templates/trans19/deleteLocation.html
{% extends "trans19/layouts/base.html" %}
{% block content %}
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Confirm Delete</h3>
            </div>
            <div class="modal-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <h4>
                        Are you sure you want to delete location: <strong>{{ object }}</strong>?
                    </h4>
                    <input  class="btn btn-danger" type="submit" value="Yes, I want to delete" />
                </form>
            </div>
            <div class="modal-footer">
                <input  class="btn btn-outline-secondary" type="submit" value="Cancel" onclick="goBack()" />
            </div>
        </div>
    </div>
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
{% endblock content %}

trans19/templates/trans19/deletePatient.html
{% extends "trans19/layouts/base.html" %}
{% block content %}
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Confirm Delete</h3>
            </div>
            <div class="modal-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <h4>
                        Are you sure you want to delete <strong>{{ object }}'s</strong> patient record?
                    </h4>
                    <input  class="btn btn-danger" type="submit" value="Yes, I want to delete" />
                </form>
            </div>
            <div class="modal-footer">
                <input  class="btn btn-outline-secondary" type="submit" value="Cancel" onclick="goBack()" />
            </div>
        </div>
    </div>
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
{% endblock content %}

trans19/templates/trans19/detail.html
{% extends "trans19/layouts/base.html" %}
{% block content %}
    <h2 class="text-center mt-5">Case {{ patient.case_number }}: {{ patient.patient_name }}</h2>
    <h4 class="text-center">Visit Record</h4>
    <div class="table-responsive w-75 mx-auto mb-5">
    <table class="table table-bordered mt-3">
        <thead class="thead-light">
            <tr>
                <th class="header">Location Visited</th>
                <th class="header">Date from</th>
                <th class="header">Date to</th>
                <th class="header">Detail</th>
                <th class="header">Category</th>
            </tr>
        </thead>
    <tbody>
        {% for visit in patient.visit_set.all %}
            <tr>
                <td>{{ visit }}</td>
                <td>{{ visit.date_from }}</td>
                <td>{{ visit.date_to }}</td>
                <td>{{ visit.detail }}</td>
                <td>{{ visit.category }}</td>
            </tr>
            {% endfor %}
    </tbody>
    </table>
    </div>
{% endblock %}

trans19/templates/trans19/formset.html
{% load crispy_forms_tags %}
{% load static %}

<div class="table-responsive">

<table class="mt-1 float-left table table-bordered table-sm">
{{ formset.management_form|crispy }}
    <tbody class="formset_row-{{ formset.prefix }}">
        {% for form in formset.forms %}
            <tr>
                {% for field in form.visible_fields %}
                    <td>
                        {% if forloop.first %}
                            {% for hidden in form.hidden_fields %}
                                {{ hidden }}
                            {% endfor %}
                        {% endif %}
                    {{ field|as_crispy_field }}
                    </td>
                 {% endfor %}
            </tr>
        {% endfor %}
    </tbody>
</table>
</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="{% static "dynamic_formsets/jquery.formset.js" %}" type="text/javascript"> </script>
<script type="text/javascript">
    $('.formset_row-{{ formset.prefix }}').formset({
        addText: 'add another',
        deleteText: 'remove',
        prefix: '{{ formset.prefix }}',
    });
</script>

trans19/templates/trans19/index.html
{% extends "trans19/layouts/base.html" %}
{% block content %}
    <div class="container mt-5">
        <h1 class="display-4">Trans-19</h1>
        <p class="lead pt-2 pl-2">A web application to maintain the database of Covid-19 Patients at CHP</p>
        <p class="lead pl-2">Total number of cases: {{ num_cases }}</p>

        {% if user.is_authenticated %}
            <p class="lead pl-2">Welcome to Trans-19, {{ user.get_username }}!</p>
            <p class="ml-2">
            <a class="btn btn-danger" href="{% url 'logout'%}?next={{request.path}}">Logout</a>
            </p>
        {% else %}
            <p class="ml-2">
                <a class="btn btn-primary" href="{% url 'login'%}?next={{request.path}}">Login</a>
            </p>
        {% endif %}
    </div>
{% endblock %}

trans19/templates/trans19/locations.html
{% extends "trans19/layouts/base.html" %}
{% block content %}
    <h2 class="text-center mt-5">Location Record</h2>
    <div class="table-responsive w-75 mx-auto mb-5">
        {%  if latest_location_list %}
    <table class="table table-bordered mt-3">
        <thead class="thead-light">
            <tr>
                <th class="header">Location</th>
                <th class="header">Address</th>
                <th class="header">District</th>
                <th class="header">X Coord</th>
                <th class="header">Y Coord</th>
                <th class="header">Modify</th>
            </tr>
        </thead>
        <tbody>
            {% for location in latest_location_list %}
            <tr>
                <td>{{ location }}</td>
                <td>{{ location.address }}</td>
                <td>{{ location.district }}</td>
                <td>{{ location.x_coord }}</td>
                <td>{{ location.y_coord }}</td>
                <td>
                    <a href="{% url 'trans19:location_edit' pk=location.pk %}">Edit</a>
                    <a href="{% url 'trans19:location_delete' pk=location.pk %}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
     {%  else %}
        <p class="lead text-center mt-5">No locations are available.</p>
    {%  endif %}
    </div>
{% endblock %}

trans19/templates/trans19/patients.html
{% extends "trans19/layouts/base.html" %}
{% block content %}
    <h2 class="text-center mt-5">Patient Record</h2>
    <div class="table-responsive w-75 mx-auto mb-5">
    {%  if latest_patient_list %}
    <table class="table table-bordered mt-3">
        <thead class="thead-light">
            <tr>
                <th class="header">Patient Name</th>
                <th class="header">ID number</th>
                <th class="header">Date of birth</th>
                <th class="header">Date case confirmed</th>
                <th class="header">Case number</th>
                <th class="header">Location(s) Visited</th>
                <th class="header">Modify</th>
            </tr>
        </thead>
    <tbody>
    {% for patient in latest_patient_list %}
            <tr>
                <td>{{ patient.patient_name }}</td>
                <td>{{ patient.patient_id }}</td>
                <td>{{ patient.date_of_birth }}</td>
                <td>{{ patient.date_case_confirmed }}</td>
                <td>{{ patient.case_number }}</td>
                <td><a href="{% url 'trans19:detail' patient.id %}">Visit Record</a></td>
                <td>
                    <a href="{% url 'trans19:patient_edit' pk=patient.pk %}">Edit</a>
                    <a href="{% url 'trans19:patient_delete' pk=patient.pk %}">Delete</a>
                </td>
            </tr>
            {% endfor %}
    </tbody>
    </table>
    {%  else %}
        <p class="lead text-center mt-5">No patients are available.</p>
    {%  endif %}
    </div>
{% endblock %}